# Generated by Django 5.2.7 on 2026-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Assigned', 'Assigned')], default='Free', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
