# Generated by Django 5.1.5 on 2026-04-11 00:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parking_area_basement_requested_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrequest',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='parkingrequest',
            name='requested_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotassignment',
            name='booked_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='slotassignment',
            name='booked_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotassignment',
            name='booked_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotassignment',
            name='overstay_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='slotassignment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
