# Generated by Django 5.1.5 on 2026-04-11 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingrequest_duration_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slotassignment',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VehicleScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('camera', 'Camera'), ('upload', 'Upload')], default='upload', max_length=10)),
                ('status', models.CharField(choices=[('authorized', 'Authorized'), ('already_inside', 'Already Inside'), ('no_booking', 'No Booking'), ('unregistered', 'Unregistered'), ('unreadable', 'Unreadable')], default='unreadable', max_length=20)),
                ('scan_image', models.ImageField(upload_to='anpr_scans/')),
                ('detected_plate', models.CharField(blank=True, max_length=20)),
                ('bounding_box', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_scan_logs', to='parking.slotassignment')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
