# Generated by Django 5.1.5 on 2026-05-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_vehiclescanlog_gate_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclescanlog',
            name='status',
            field=models.CharField(choices=[('authorized', 'Authorized'), ('already_inside', 'Already Inside'), ('exited', 'Exited'), ('already_outside', 'Already Outside'), ('no_booking', 'No Booking'), ('unregistered', 'Unregistered'), ('unreadable', 'Unreadable')], default='unreadable', max_length=20),
        ),
    ]
